# Generated by Django 2.2 on 2019-04-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body_text',
            field=models.TextField(default='exit', verbose_name='input text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='publication_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
    ]
